// Generated by npm run diagrams:sany; preserves layout before lazy SVG loading.
export const sanyDiagramSizes = {
  "clock-mapping-zh": {
    "desktop": {
      "width": 1069,
      "height": 379
    },
    "mobile": {
      "width": 395,
      "height": 696
    }
  },
  "clock-mapping-en": {
    "desktop": {
      "width": 1323,
      "height": 379
    },
    "mobile": {
      "width": 399,
      "height": 784
    }
  },
  "dual-timeline-zh": {
    "desktop": {
      "width": 1172,
      "height": 762
    },
    "mobile": {
      "width": 394,
      "height": 1232
    }
  },
  "dual-timeline-en": {
    "desktop": {
      "width": 1247,
      "height": 762
    },
    "mobile": {
      "width": 455,
      "height": 1302
    }
  }
} as const;
