import { PortfolioImage as Image } from "../portfolio-image";
import Link from "next/link";
import { T } from "../localized";
import { SiteFooter, SiteHeader } from "../site-shell";
import { ReorderBufferDemo } from "./ReorderBufferDemo";
import { WaterbagCodeLinks } from "../project-evidence";

function MultiLightFigure() {
  const lights = [
    { key: "BACKLIGHT", zh: "背光", en: "Backlight", defectZh: "毛发 / 针孔 / 透射异常", defectEn: "Fibers / pinholes / transmission" },
    { key: "DARK FIELD", zh: "双侧暗场", en: "Side dark field", defectZh: "划痕 / 细线", defectEn: "Scratches / fine lines" },
    { key: "POLARIZED", zh: "交叉偏振", en: "Cross polarization", defectZh: "反光抑制 / 浅色污染", defectEn: "Glare control / pale contamination" },
  ];
  return <figure className="compact-figure vision-light"><div className="compact-figure-heading"><span>FIGURE 01 / CONCEPTUAL LIGHT COMPARISON</span><h3><T zh="同一只袋子，三种观察条件" en="One bag under three lighting paths" /></h3></div><div className="vision-light-views">{lights.map((light, index) => <div key={light.key}><span>{light.key}</span><div className={`vision-light-sample vision-light-sample-${index}`} aria-hidden="true"><i /><b /><em /></div><strong><T zh={light.zh} en={light.en} /></strong><small><T zh={light.defectZh} en={light.defectEn} /></small></div>)}</div><figcaption><T zh="图形只说明不同光路如何改变缺陷可见性，并非真实缺陷对比照片。真实工位照片见页首。" en="The graphics illustrate how lighting changes defect visibility; they are not real defect comparison photos. The real inspection station appears above." /></figcaption></figure>;
}

function BagPipeline() {
  return <figure className="compact-figure vision-pipeline"><div className="compact-figure-heading"><span>FIGURE 02 / BAG-LEVEL PIPELINE</span><h3><T zh="采图、检测、分拣、追溯是一条链" en="Capture, inspect, sort, and trace form one path" /></h3></div><ol><li><span>01 / CAPTURE</span><strong><T zh="A / B 面 × 三光路" en="A / B sides × three lights" /></strong><small>6 frames / Bag ID</small></li><li><span>02 / INSPECT</span><strong><T zh="整图粗检 + ROI 精检" en="Full image + ROI refinement" /></strong><small>YOLO → ONNX / CUDA</small></li><li><span>03 / ORDER</span><strong><T zh="袋级状态与结果重排" en="Bag state + result reorder" /></strong><small>Concurrent workers → physical order</small></li><li><span>04 / ACT</span><strong><T zh="PLC 分拣与确认" en="PLC sorting + ACK" /></strong><small>OK / NG</small></li><li><span>05 / TRACE</span><strong><T zh="生产记录可回查" en="Queryable production record" /></strong><small>JSONL → SQLite</small></li></ol><figcaption><T zh="采集线程只接收完整帧，推理与保存移出回调；缺帧、超时或无效采图不会作为正常袋继续分拣。" en="Capture callbacks receive complete frames while inference and storage run elsewhere. Missing, timed-out, or invalid capture does not silently continue as a normal bag." /></figcaption></figure>;
}

function TraceRecordFigure() {
  return <figure className="compact-figure vision-record"><div className="compact-figure-heading"><span>FIGURE 04 / TRACEABILITY</span><h3><T zh="一只袋子的记录应该能还原一次决策" en="One Bag ID should explain one decision" /></h3></div><div className="vision-record-grid"><div><span>BAG ID</span><strong>000142</strong><small><T zh="示例编号" en="Illustrative ID" /></small></div><div><span>CAPTURE</span><strong>A/B × 3</strong><small><T zh="六帧与光源元数据" en="Six frames + light metadata" /></small></div><div><span>INFERENCE</span><strong>boxes + reason</strong><small><T zh="检测框、原因、阶段耗时" en="Boxes, reason, stage timing" /></small></div><div><span>CONTROL</span><strong>OK / NG + ACK</strong><small><T zh="分拣动作与确认" en="Sort action + acknowledgement" /></small></div></div><div className="vision-record-flow"><span>JSONL <T zh="审计源" en="audit source" /></span><b>→</b><span>SQLite <T zh="索引" en="index" /></span><b>→</b><span>Dashboard <T zh="查询 / 回放" en="query / replay" /></span></div><figcaption><T zh="编号是示例。真实记录还关联相机、状态轨迹与异常；页面不展示客户生产数据。" en="The ID is illustrative. Production records also link cameras, state traces, and exceptions; no client production data is shown." /></figcaption></figure>;
}

function TraceRecord() {
  return <><TraceRecordFigure /><WaterbagCodeLinks kind="trace" /></>;
}

export function IndustrialVisionInspection() {
  return <main className="compact-case compact-vision"><SiteHeader active="projects" /><article>
    <header className="compact-hero compact-hero-vision"><div><Link className="compact-back" href="/projects">← <T zh="项目案例" en="Projects" /></Link><p className="compact-kicker">INDUSTRIAL VISION / 2025</p><h1><T zh="工业水样袋视觉检测" en="Industrial Vision Inspection" /></h1><p className="compact-lead"><T zh="面对半透明、低对比度材料，将多光源采图、两阶段缺陷检测、Bag ID 有序分拣与生产追溯做成一条可运行的工业视觉链路。" en="For translucent, low-contrast bags, an industrial vision path connects multi-light capture, two-stage defect detection, Bag-ID ordered sorting, and production traceability." /></p><div className="compact-hero-meta"><span>C++17</span><span>Industrial Camera</span><span>ONNX / CUDA</span><span>Modbus TCP</span></div></div><figure className="vision-hero-photo"><Image src="/images/projects/缺陷检测装置1.png" alt="工业水样袋缺陷检测装置实拍" width={1122} height={1402} unoptimized priority sizes="(max-width: 900px) 350px, 32vw" /><figcaption><T zh="工业水样袋检测装置实拍" en="Industrial waterbag inspection station" /></figcaption></figure></header>

    <dl className="compact-metrics"><div><dt><T zh="整体缺陷 Recall" en="Overall defect recall" /></dt><dd>≈97%</dd></div><div><dt><T zh="相较单级检测" en="Above single-stage inspection" /></dt><dd>+6 pp</dd></div><div><dt><T zh="六帧 / 袋端到端时延" en="Six-frame per-bag latency" /></dt><dd>≈200 ms</dd></div></dl>
    <section className="compact-section compact-section-first compact-section-split"><div className="compact-section-heading"><span>01 / IMAGING</span><h2><T zh="让微弱缺陷先变得可见" en="Make subtle defects visible first" /></h2><p><T zh="单张正面光图像容易把折痕、反光与真实缺陷混在一起。" en="A single front-lit image can confuse folds, glare, and real defects." /></p></div><div className="compact-prose"><p><T zh="人工检测会改变观察角度；平放的设备无法直接复制这一动作。方案以背光、双侧暗场与交叉偏振的时序 Burst 获得互补视图，并按 Bag ID 把 A/B 两面共六帧组合成一个完整样本。" en="Human inspectors change viewing angle, but a flat inspection station cannot directly copy that motion. Timed backlight, side dark field, and cross-polarized bursts provide complementary views, assembled as six frames across both sides under one Bag ID." /></p></div><div className="compact-split-figure"><MultiLightFigure /></div></section>

    <section className="compact-section"><div className="compact-section-heading"><span>02 / SYSTEM PATH</span><h2><T zh="模型只是产线决策的一环" en="The model is one part of the line decision" /></h2><p><T zh="采图完整性、动作确认、物理顺序与异常记录同样影响交付。" en="Capture completeness, action acknowledgements, physical order, and exception records also determine delivery." /></p></div><BagPipeline /><WaterbagCodeLinks kind="capture" /></section>

    <section className="compact-section"><div className="compact-section-heading"><span>03 / CONCURRENCY</span><h2><T zh="把并发完成顺序与物理袋序分开" en="Separate completion order from physical bag order" /></h2></div><ReorderBufferDemo /><WaterbagCodeLinks kind="order" /></section>

    <section className="compact-section compact-section-split"><div className="compact-section-heading"><span>04 / TRACEABILITY</span><h2><T zh="从误检回查到动作追溯" en="Trace a decision back to its evidence" /></h2><p><T zh="每个 Bag ID 要能回到原图、推理结果与设备动作。" en="Every Bag ID should lead back to images, inference, and device actions." /></p></div><div className="compact-prose"><p><T zh="系统以 JSONL 保留袋级审计记录，再同步至 SQLite 与 Flask 看板。帧、相机、检测框、缺陷原因、阶段耗时、PLC ACK 与状态轨迹共同解释一次 OK / NG 决策。" en="The system keeps bag-level audit records in JSONL and synchronizes them to SQLite and a Flask dashboard. Frames, cameras, boxes, defect reasons, stage timings, PLC ACKs, and state traces explain each OK / NG decision." /></p></div><div className="compact-split-figure"><TraceRecord /></div></section>

    <section className="compact-section compact-section-split"><div className="compact-section-heading"><span>05 / OWNERSHIP & VALIDATION</span><h2><T zh="我完成的主控与验证边界" en="My controller and validation boundary" /></h2></div><div className="compact-prose"><p><T zh="我独立开发 C++ 视觉后端主控，接入工业相机、Modbus TCP、推理调度与末端分拣；参与多光源成像与粗检—微缺陷精检链路，并完成 YOLO 训练、ONNX 导出和 CUDA 部署。" en="I independently developed the C++ vision backend controller across camera, Modbus TCP, inference scheduling, and end sorting. I contributed to multi-light imaging and coarse-to-fine inspection, and handled YOLO training, ONNX export, and CUDA deployment." /></p><p><T zh="公开仓库定位为可复现的工程评审 Demo：Mock Camera / PLC 用于 CI 与无硬件回归，真实设备主路径可用 mock detector 验证采图、触发、ACK、分拣与留痕。此页不把概念图或示例 Bag ID 当作现场测量结果。" en="The public repository is a reproducible engineering review demo. Mock camera and PLC support CI and hardware-free regression; the real-device path can use a mock detector to verify capture, triggers, ACKs, sorting, and traceability. Concept diagrams and the sample Bag ID are not field measurements." /></p><a className="compact-source-link" href="https://github.com/MzKyle/Defect-detection-of-water-sampling-bags" target="_blank" rel="noreferrer"><T zh="查看公开仓库" en="View public repository" /> ↗</a></div></section>
    <div className="compact-endlinks"><Link href="/projects/sany-welding-robotics"><T zh="SANY 工业机器人案例" en="SANY industrial robotics" /> →</Link><Link href="/projects"><T zh="返回项目列表" en="All projects" /> →</Link></div>
  </article><SiteFooter /></main>;
}
