import Link from "next/link";
import { T } from "../localized";
import { SiteFooter, SiteHeader } from "../site-shell";

const hub = "/projects/sany-welding-robotics";

function RegistrationFigure() {
  return <figure className="compact-figure preweld-registration"><div className="compact-figure-heading"><span>FIGURE 01 / REGISTRATION PIPELINE</span><h3><T zh="从两组点云到一次高度修正" en="From two point clouds to a height correction" /></h3></div><div className="preweld-pipeline"><div><small>REFERENCE</small><strong><T zh="预存工件点云" en="Stored workpiece cloud" /></strong></div><i>+</i><div><small>OBSERVATION</small><strong><T zh="实时 3D 观测" en="Live 3D observation" /></strong></div><i>→</i><div><small>ALIGN</small><strong><T zh="空间配准" en="Spatial registration" /></strong></div><i>→</i><div><small>OUTPUT</small><strong>Δheight</strong></div></div><figcaption><T zh="管线为公开版概念示意。具体标定、配准实现和设备通信细节未在公开材料中披露。" en="Public conceptual pipeline. Calibration, registration implementation, and device communication details are not disclosed in the public material." /></figcaption></figure>;
}

function CoordinateFigure() {
  return <figure className="compact-figure preweld-coordinate"><div className="compact-figure-heading"><span>FIGURE 02 / COORDINATE FRAMES</span><h3><T zh="把观测放回机器人坐标" en="Bring observations into robot coordinates" /></h3></div><svg viewBox="0 0 600 230" role="img" aria-label="Camera, TCP and robot base coordinate relationships shown conceptually"><path d="M64 177H538M64 177V35" className="compact-axis" /><path d="M180 150 L340 91 L470 130" className="compact-line" /><circle cx="180" cy="150" r="9" /><circle cx="340" cy="91" r="9" /><circle cx="470" cy="130" r="9" /><text x="120" y="185">ROBOT BASE</text><text x="303" y="72">TCP POSE</text><text x="432" y="160">3D OBSERVATION</text></svg><figcaption><T zh="使用机器人 TCP 位姿和已知坐标关系关联参考点云与实时观测；图不表示具体安装结构或私有标定参数。" en="Robot TCP pose and known coordinate relations connect reference and live clouds. This diagram does not depict the exact installation or private calibration values." /></figcaption></figure>;
}

export function PreWeldLocalization() {
  return <main className="compact-case"><SiteHeader active="projects" /><article>
    <header className="compact-hero compact-hero-small"><div><Link className="compact-back" href={hub}>← <T zh="SANY 项目总览" en="SANY experience hub" /></Link><p className="compact-kicker">SANY / ENGINEERING MODULE 02</p><h1><T zh="焊前 3D 点云定位" en="Pre-weld 3D localization" /></h1><p className="compact-lead"><T zh="将预存工件点云、实时 3D 观测与机器人 TCP 位姿放到一致的空间关系中，计算焊前高度纠偏量。" en="Relate a stored workpiece point cloud, live 3D observations, and robot TCP pose in one spatial frame to derive a pre-weld height correction." /></p><div className="compact-hero-meta"><span>3D Camera</span><span>Point Cloud</span><span>TCP Pose</span><span>Robot Integration</span></div></div><aside className="compact-result"><span>PUBLIC RESULT / PRE-WELD ONLY</span><strong>±0.5 mm</strong><p><T zh="公开的焊前定位结果；不用于表示摆弧焊选帧或整机定位精度。" en="Public pre-weld localization result; it does not describe weave-frame selection or overall robot accuracy." /></p></aside></header>

    <section className="compact-section compact-section-first"><div className="compact-section-heading"><span>01 / PROBLEM</span><h2><T zh="在焊接前找到工件的实际高度" en="Find the workpiece height before welding" /></h2></div><div className="compact-prose"><p><T zh="离线保存的工件几何不能直接当作当前工位的实际位置。系统需要把参考 3D 点云和相机的实时观测对齐，再结合机器人 TCP 位姿，把几何差异转成可用于执行的高度修正。" en="Stored geometry is not the live workpiece position. The system relates the reference cloud to a camera observation, then uses robot TCP pose to turn the geometric difference into an actionable height correction." /></p></div><RegistrationFigure /></section>

    <section className="compact-section compact-section-split"><div className="compact-section-heading"><span>02 / COORDINATES</span><h2><T zh="配准结果必须进入机器人的坐标语境" en="Registration must reach the robot's frame" /></h2><p><T zh="相机里的高度差不能直接作为机器人指令。" en="A camera-frame difference cannot directly become a robot command." /></p></div><div className="compact-prose"><p><T zh="处理链路先明确参考点云、实时观测与 TCP 位姿各自的坐标系，再使用标定得到的关系完成空间关联。这里重点是数据和坐标的接口边界，而不是宣称一个未公开的具体求解器由我独立实现。" en="The path identifies the frames of the reference cloud, live observation, and TCP pose, then uses calibrated relations to connect them. The engineering focus here is the data and frame boundary; the detailed solver is not claimed as my independent implementation." /></p><CoordinateFigure /></div></section>

    <section className="compact-section compact-section-split"><div className="compact-section-heading"><span>03 / ROBOT INTEGRATION</span><h2><T zh="从纠偏量到机器人执行" en="From correction to robot execution" /></h2><p><T zh="公开版只展示系统交接与恢复边界。" en="The public view shows handoff and recovery boundaries only." /></p></div><div className="compact-prose"><div className="preweld-handoff"><span><T zh="观测有效性" en="Observation validity" /></span><b>→</b><span><T zh="高度修正量" en="Height correction" /></span><b>→</b><span><T zh="接口交接" en="Robot handoff" /></span><b>→</b><span><T zh="执行确认" en="Execution confirmation" /></span></div><p><T zh="对外展示的核心约束是：无效观测、坐标不一致或未确认的执行结果不应继续流入下一步。FANUC 通信的私有报文、现场动作参数和具体恢复策略不在公开页展开。" en="The public invariant is that invalid observations, mismatched frames, or unconfirmed execution must not silently advance. Private FANUC messages, field parameters, and specific recovery policies are omitted." /></p></div></section>

    <section className="compact-section compact-section-split"><div className="compact-section-heading"><span>04 / OWNERSHIP & EVIDENCE</span><h2><T zh="参与范围与结果边界" en="Contribution and evidence boundary" /></h2></div><div className="compact-prose"><p><T zh="我参与了预存工件点云、机器人 TCP 位姿与实时观测的空间配准和高度纠偏集成。这是 SANY 工作中的第二条技术线，与我重点设计的摆弧焊相位感知链路分开陈述。" en="I contributed to registration and height-correction integration across stored clouds, TCP pose, and live observations. This is the second SANY workstream, separate from my primary phase-aware weave-vision design." /></p><p><T zh="±0.5 mm 是公开材料中的焊前定位结果；公开资料未给出完整测量条件，因此此页不延伸出重复性、统计置信度或端到端焊接精度结论。" en="The ±0.5 mm value is the public pre-weld localization result. The public material does not provide full test conditions, so this page does not infer repeatability, statistical confidence, or end-to-end welding accuracy." /></p></div></section>
    <div className="compact-endlinks"><Link href={hub}><T zh="返回 SANY 总览" en="Back to SANY hub" /> →</Link><Link href={`${hub}/technical`}><T zh="阅读摆弧焊技术长文" en="Read the weave-vision essay" /> →</Link></div>
  </article><SiteFooter /></main>;
}
