import type { Metadata } from "next";
import Link from "next/link";
import { experiences, projects } from "../../lib/portfolio";
import { Localized, T } from "../../components/localized";
import { SiteFooter, SiteHeader } from "../../components/site-shell";
export const metadata: Metadata = { title: "简历 | 王凯豪", description: "王凯豪的机器人软件开发工程师在线简历。" };

export default function ResumePage() {
  return <main><SiteHeader active="resume" /><section className="resume-hero"><div><p className="section-kicker"><T zh="在线简历" en="RESUME" /></p><h1><T zh="王凯豪" en="Kyle Wang" /></h1><p><T zh="机器人软件开发工程师" en="Robotics Software Engineer" /></p></div><div><a className="button button-primary" href="/resume.pdf" target="_blank" rel="noreferrer"><T zh="下载 PDF" en="Download PDF" /> <span>↓</span></a><a className="button button-secondary" href="mailto:2972689924@qq.com"><T zh="联系我" en="Contact me" /> <span>↗</span></a></div></section>
    <section className="resume-layout section-shell"><aside><div><span><T zh="联系方式" en="CONTACT" /></span><a href="mailto:2972689924@qq.com">2972689924@qq.com</a><a href="tel:19862681939">19862681939</a><a href="https://github.com/MzKyle">github.com/MzKyle</a></div><div><span><T zh="教育经历" en="EDUCATION" /></span><strong><T zh="青岛大学" en="Qingdao University" /></strong><p><T zh="电子信息工程" en="Electronic Information Engineering" /><br /><T zh="卓越工程师计划" en="Excellence Engineer Program" /><br />2023.09 — 2027.06</p></div><div><span><T zh="核心技术" en="CORE STACK" /></span><ul><li>C++ / CMake</li><li>ROS 2 / TF</li><li>OpenCV / PCL</li><li>ONNX / TensorRT</li><li>Linux / PTP</li><li>Qt / Python</li></ul></div></aside><div className="resume-main"><section><h2><T zh="个人简介" en="SUMMARY" /></h2><p className="resume-summary"><T zh="拥有工业焊接机器人、物流体积测量、工业缺陷检测和 RoboMaster 实战经验，能够独立承担传感器接入、数据处理、算法集成、机械臂控制、仿真验证与工程工具开发，具备快速进入机器人软件与工业视觉岗位的综合能力。" en="Robotics software engineer with hands-on experience in industrial welding robots, logistics volume measurement, visual defect inspection, and RoboMaster. Able to own sensor integration, data processing, algorithm deployment, robot control, simulation validation, and engineering tools." /></p></section><section><h2><T zh="工作经历" en="EXPERIENCE" /></h2>{experiences.map((item) => <article key={item.company.zh}><div><span>{item.period}</span><h3><Localized text={item.company} /></h3><strong><Localized text={item.role} /></strong></div><ul>{item.details.map((detail) => <li key={detail.zh}><Localized text={detail} /></li>)}</ul></article>)}</section><section><h2><T zh="代表项目" en="SELECTED PROJECTS" /></h2>{projects.slice(0, 3).map((project) => <article key={project.slug}><div><span>{project.year}</span><h3>{project.title}</h3><strong><Localized text={project.subtitle} /></strong></div><p><Localized text={project.summary} /></p><Link className="text-link" href={`/projects/${project.slug}`}><T zh="查看项目案例" en="View case study" /> →</Link></article>)}</section><section><h2><T zh="荣誉奖项" en="HONORS" /></h2><ul className="honor-list"><li><T zh="全国大学生机器人竞赛全国三等奖" en="National College Student Robotics Competition — Third Prize" /></li><li><T zh="全国大学生机器人竞赛区域赛二等奖" en="Regional Robotics Competition — Second Prize" /></li><li><T zh="RoboMaster 高校联盟赛二等奖、机器人竞技一等奖" en="RoboMaster University League — Second Prize; Robot Competition — First Prize" /></li><li><T zh="全国大学生电子设计大赛省级二等奖" en="National Electronics Design Contest Provincial — Second Prize" /></li></ul></section></div></section><section className="pdf-preview section-shell"><div><p className="section-kicker"><T zh="PDF 简历" en="RESUME PDF" /></p><h2><T zh="完整简历" en="Full resume" /></h2><a href="/resume.pdf" target="_blank" rel="noreferrer"><T zh="在新窗口打开" en="Open in a new window" /> ↗</a></div><iframe src="/resume.pdf" title="王凯豪简历 PDF / Kyle Wang resume PDF" /></section><SiteFooter /></main>;
}
